In [2]:
import pandas as pd
data = [['bola', 10], ['dayo', 15], ['femi', 20]]
df = pd.DataFrame (data, columns = ['Name', 'Age'])
df

Name  Age
0  bola   10
1  dayo   15
2  femi   20

In [1]:
import pandas as pd
data = {'Name': ['QueenBee','Harnaf','Richy', 'Liberty','Hardman', ] ,'Matric No':['NSS/2019/006', 'CSE/2019/006', 'NSS/2019/006','CSE/2019/006','CHT/2019/002'], 'Department':['Networking and System Security', 'Software Engineering', 'Networking and System Security','Software Engineering', 'Hardware Engineering']}
df = pd.DataFrame (data)
df

Name     Matric No                      Department
0  QueenBee  NSS/2019/006  Networking and System Security
1    Harnaf  CSE/2019/006            Software Engineering
2     Richy  NSS/2019/006  Networking and System Security
3   Liberty  CSE/2019/006            Software Engineering
4   Hardman  CHT/2019/002            Hardware Engineering

In [2]:
import numpy as np
matr = np.array([[1, 2], [3, 4]])
print(matr)
print('The shape of Z is' , matr.shape)

[[1 2]
 [3 4]]
The shape of Z is (2, 2)


In [9]:
import pandas as pd
Excel_df = pd.read_csv ('desktop/AIInvasion.csv' )
Excel_df


S/N             STATE  AREA(km2)  POPULATION
0     0        Abia State       6320     2845380
1     1     Adamawa State      36917     3178950
2     2  Akwa Ibom State        7081     3178950
3     3     Anambra State       4844     4177828
4     4      Bauchi State      45837     4653066
5     5     Bayelsa State      10773     1704515
6     6       Benue State      34059     4253641
7     7       Borno State      70898     4171104
8     8       Cross River      20156     2892988
9     9       Delta State      17698     4112445
10   10      Ebonyi State       5670     2176947
11   11         Edo State      17802     3233366
12   12       Ekiti State       6353     2398957
13   13       Enugu State       7161     3267837
14   14               FCT       7315     1405201
15   15       Gombe State      18768     2365040
16   16         Imo State       5530     3927563
17   17      Jigawa State      23154     4361002
18   18      Kaduna State      46053     6113503
19   19        Kano State      20131     9401288
20   20     Katsina State      24192     5801584
21   21       Kebbi State      36800     3256541
22   22        Kogi State      29833     3314043
23   23       Kwara State      36825     2365353
24   24       Lagos State       3345     9113605
25   25    Nasarawa State      27117     1869377
26   26       Niger State      76363     3954772
27   27        Ogun State      16762     3751140
28   28        Ondo State      15500     3460877
29   29        Osun State       9251     3416959
30   30         Oyo State      28454     5580894
31   31     Plateau State      30913     3206531
32   32      Rivers State      11077     5198605
33   33      Sokoto State      25973     3702676
34   34      Taraba State      54473     2294800
35   35        Yobe State      45502     2321339
36   36     Zamfara State      39762     3278873

In [10]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
z = np.array([1,2,3])
x.T
print (x+y)
print (np.add(x,y))

[[3 4 5]
 [7 8 9]]
[[3 4 5]
 [7 8 9]]


In [11]:
A10 = np.arange(10)
A10
print(A10.shape)

(10,)
